// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzYSXyYQqymLrjn-3I963O0FytzSkvZmM',
    appId: '1:890422525980:web:2e190dc467301ed4de1fd9',
    messagingSenderId: '890422525980',
    projectId: 'cheers-9b14e',
    authDomain: 'cheers-9b14e.firebaseapp.com',
    storageBucket: 'cheers-9b14e.appspot.com',
    measurementId: 'G-8KCF8FXP4J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9NkIsfOIQev1PXu4iSeSCls5SSMlVa10',
    appId: '1:890422525980:android:8127371889bb60b2de1fd9',
    messagingSenderId: '890422525980',
    projectId: 'cheers-9b14e',
    storageBucket: 'cheers-9b14e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBU1nikEb7SII-ZovyV6cCIDLR8uHKKJ3w',
    appId: '1:890422525980:ios:fbf70da1abffc86cde1fd9',
    messagingSenderId: '890422525980',
    projectId: 'cheers-9b14e',
    storageBucket: 'cheers-9b14e.appspot.com',
    iosClientId:
        '890422525980-o6l0v3j47hlg7c5odqe1jukuss0isb61.apps.googleusercontent.com',
    iosBundleId: 'com.urxstudios.cheers',
  );
}
